app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UsersController

#product:
#    type:     rest
#    resource: AppBundle\Controller\ProductController

#test:
#    path: /about
#    defaults: { _controller: AppBundle:Users:getDemos }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"